### PR TITLE
U/danielsf/ref cat

### PR DESCRIPTION
**Pull request by danielsf**
this PR adds the script to generate reference catalogs for DC2

### CODE REVIEW

**Comment by jchiang87** [comment]
@danielsf Is there a way of saving the extragalactic catalog name (the actual one, not just an alias) as metadata in the reference catalog and potentially in its downstream derivations?  As we've seen, having that info more readily available would make provenance tracking much easier.

**Comment by danielsf** [comment]
Yes.  I will add that.

**Comment by danielsf** [comment]
Note, I am going to close this PR and move to `u/danielsf/refCat2`.  There was some non-trivial rebasing needed to get this branch built on top of master.

**Comment by evevkovacs** [comment]
@jchiang87 @danielsf The extra-galactic catalog has a version number included in the metadata, which could/should be transferred to the instance catalog, if I am understanding correctly what you are asking for.

**Pull request closed without merging**
