### PR TITLE
Assign agn params

### PR DESCRIPTION
**Pull request by danielsf**
This PR implements adds variable AGN to protoDC2.

The designed workflow is this:

- Sometime before generating the InstanceCatalogs, the user will run `bin.src/create_agn_db.py`, which will create a sqlite database associating the protoDC2 galaxies with their AGN variability parameters.  This script has the ability to impose a cutoff in black hole mass and observed i-band magnitude.  Cuts of `Mbh>=10**7 Msun` and `m_i<=30` result in a database of 240MB.

- When generating the InstanceCatalogs, the user sets the `agn_params_db` member of `agnDESCQAObject_protoDC2` equal to the path to the AGN parameter database created above.  The `agnDESCQAObject_protoDC2` will then query the AGN parameter database as InstanceCatalogs are generated, associating the variability parameters with the AGN and passing them along to the CatSim variability model.

This scheme may actually be more optimal for DC2, when we cannot load all of the galaxies into memory at once, than it is for protoDC2, when we can.  If the InstanceCatalog generation for protoDC2 proceeds too slowly, we can try something more memory-intensive to rapidly associate variability parameters with AGN, but I don't think that will be necessary.

### CODE REVIEW

**Comment by danielsf** [comment]
You will need `master` branches of `sims_catUtils` and `sims_utils` to actually run this PR.  I will issue a new tagged version of `lsst_sims` tomorrow, since I think we are done developing on the LSST side, at least for protoDC2.

**Comment by drphilmarshall** [comment]
For scientific discussion of the AGN assignment, including analysis of the M_BH and magnitude cuts, check out the discussion and plots in https://github.com/LSSTDESC/DC2_Repo/issues/55 . Thanks, @danielsf ! :-)

**Comment by jbkalmbach** [comment]
I wasn't able to run a basic `compoundInstanceCatalog` with the AGN included because the default values dict isn't adapting to the compound framework.

Here's my code:

```                                                                                        
from desc.sims.GCRCatSimInterface import CompoundDESCQAInstanceCatalog
from desc.sims.GCRCatSimInterface import bulgeDESCQAObject_protoDC2
from desc.sims.GCRCatSimInterface import diskDESCQAObject_protoDC2
from desc.sims.GCRCatSimInterface import agnDESCQAObject_protoDC2
from desc.sims.GCRCatSimInterface import CompoundDESCQAObject
from lsst.sims.catalogs.definitions import InstanceCatalog
from lsst.sims.utils import arcsecFromRadians
from lsst.sims.utils import ObservationMetaData
import numpy as np

class _testDESCQAObj(object):
    yaml_file_name = 'proto-dc2_v2.1.2'
    field_ra = 23.0
    field_dec = -22.3

class bulgeDESCQAObject_test(_testDESCQAObj, bulgeDESCQAObject_protoDC2):
    objid = 'bulge_descqa'

class diskDESCQAObject_test(_testDESCQAObj, diskDESCQAObject_protoDC2):
    objid = 'disk_descqa'

class agnDESCQAObject_test(_testDESCQAObj, agnDESCQAObject_protoDC2):
    objid = 'agn_descqa'

class CatForBulge(InstanceCatalog):
    column_outputs = ['uniqueId', 'objid', 'galaxy_id', 'raJ2000', 'decJ2000',
                      'minorAxis', 'majorAxis']
    transformations = {'minorAxis': arcsecFromRadians,
                       'majorAxis': arcsecFromRadians,
                       'raJ2000': np.degrees,
                       'decJ2000': np.degrees}

    def get_objid(self):
        return np.array([self.db_obj.objectTypeId]*len(self.column_by_name('raJ2000')))

class CatForDisk(InstanceCatalog):
    column_outputs = ['uniqueId', 'objid', 'galaxy_id', 'raJ2000', 'decJ2000',
                      'minorAxis']
    transformations = {'minorAxis': arcsecFromRadians,
                       'raJ2000': np.degrees,
                       'decJ2000': np.degrees}


    def get_objid(self):
        return np.array([self.db_obj.objectTypeId]*len(self.column_by_name('raJ2000')))

class CatForAgn(InstanceCatalog):
    column_outputs = ['uniqueId', 'objid', 'galaxy_id', 'raJ2000', 'decJ2000', 'magNorm']

    transformations = {'raJ2000': np.degrees,
                       'decJ2000': np.degrees}


    def get_objid(self):
        return np.array([self.db_obj.objectTypeId]*len(self.column_by_name('raJ2000')))



if __name__ == "__main__":

    obs = ObservationMetaData(pointingRA=22.7, pointingDec=-22.7,
                              boundType='circle', boundLength=0.01)

    cat = CompoundDESCQAInstanceCatalog([CatForBulge, CatForDisk, CatForAgn],
                                        [bulgeDESCQAObject_test,
                                         diskDESCQAObject_test,
                                         agnDESCQAObject_test],
                                        obs_metadata=obs,
                                        compoundDBclass=CompoundDESCQAObject)

    cat.write_catalog('descqa_compound_cat.txt', chunk_size=10000)
```

and my error:

```
Traceback (most recent call last):
  File "make_compound_catalog.py", line 71, in <module>
    cat.write_catalog('descqa_compound_cat.txt', chunk_size=10000)
  File "/global/homes/b/brycek/DC2/sims_catalogs/python/lsst/sims/catalogs/definitions/CompoundInstanceCatalog.py", line 242, in write_catalog
    write_mode=write_mode)
  File "/global/homes/b/brycek/DC2/sims_catalogs/python/lsst/sims/catalogs/definitions/CompoundInstanceCatalog.py", line 297, in _write_compound
    for chunk in master_results:
  File "/global/homes/b/brycek/DC2/sims_GCRCatSimInterface_danielsf/python/desc/sims/GCRCatSimInterface/DatabaseEmulator.py", line 119, in __next__
    dtype_list.append((name, self._default_values[name][1]))
KeyError: 'agn_descqa_magNorm'
```

**Comment by jbkalmbach** [comment]
To note: It did work when `magNorm` was not included in the AGN Catalog definition.

**Comment by danielsf** [comment]
@jbkalmbach So: you are expecting something named`agn_descqa_magNorm` and it isn't there?

I think the problem is that I forgot to explicitly define an `objid` in `agnDESCQAObject_protoDC2`.  I will add a commit doing that.

**Comment by danielsf** [comment]
@jbkalmbach 

pull and try it now

**Comment by jbkalmbach** [comment]
No, unfortunately that didn't do it.

**Comment by jchiang87** [comment]
@danielsf Would it be possible to move these changes to a branch of the LSSTDESC repo?   We'll need to update `InstanceCatalogWriter.py` and `generateInstCat.py` to use this new code.  I'm in the process of doing that already to make sure I understand how everything will work, and I think it would be easier to manage if I could just push those changes to the branch with these changes.

**Comment by danielsf** [comment]
Sure.  Just a second.

**Comment by danielsf** [comment]
There is now an `assign_agn_params` branch on the LSSTDESC version of this repository.  The final PR will be resolved there.

**Pull request closed without merging**
