### PR TITLE
Rotate dc2 field

### PR DESCRIPTION
**Pull request by danielsf**
This pull request will allow us to rotate protoDC2 into whatever field we want.  One just needs to use `bulgeDESCQAObject_protoDC2` and `diskDESCQAObject_protoDC2`, specifying the center of the new field by
```
db = bulgeDESCQAObject_protoDC2('proto-dc2_v2.1.2')
db.field_ra = newRA  # in degrees
db.field_dec = newDec  # in degrees
```

### CODE REVIEW

**Comment by danielsf** [comment]
@jchiang87 I can't seem to assign a reviewer to this PR.  I am @-ing you so that you see it.

**Comment by jchiang87** [comment]
Thanks, Scott.  I just assigned myself.  I wanted to look into the settings to see why you can't assign a reviewer, but I don't seem to have access, despite having created this repo.

**Comment by jchiang87** [comment]
Hi @danielsf,
Thanks!  I tried this with the `generateInstCat.py` script using a couple of `minion_1016_sqlite.db` visits: `obsHistID = 1418971`, which is near RA, Dec = (0, 0), and `obsHistID = 230`, which is centered on `fieldID = 1427`, our nominal location for the uDDF in Run1.1.   For both cases, I set the `field_[RA,Dec]` values to the nominal visit pointing dirs and got seemingly identical lists of protoDC2 galaxies which only differed in the object RA, Dec values:
```
[cori12] wc gal_cat*.txt
   70283  1616509 17458397 gal_cat_1418971.txt
   70283  1616509 17255269 gal_cat_230.txt
  140566  3233018 34713666 total
[cori12] head -2 gal_cat_1418971.txt
object 221977697 0.172765773 -0.0366500546 28.769253855155185 galaxySED/Inst.32E09.04Z.spec.gz 0.572623968 0.00067739567 0.00157897884 0.0460245758 0 0 sersic2d 0.1423787 0.13019674 4593.39727 4 CCM 0.0235312717 3.59999681 CCM 0.0966574944 3.1
object 222109793 0.146192527 -0.110754807 27.105716765193463 galaxySED/Burst.50E09.02Z.spec.gz 0.567668319 -0.00274533196 -0.0119206831 0.0424999148 0 0 sersic2d 0.191045119 0.186344383 8427.47647 4 CCM 0.0410986647 3.65929992 CCM 0.101886877 3.1
[cori12] head -2 gal_cat_230.txt
object 221977697 54.5081415 -27.7877042 28.769253855155185 galaxySED/Inst.32E09.04Z.spec.gz 0.572623968 0.00067739567 0.00157897884 0.0460245758 0 0 sersic2d 0.1423787 0.13019674 4593.39727 4 CCM 0.0235312717 3.59999681 CCM 0.0353178123 3.1
object 222109793 54.5000713 -27.8661052 27.105716765193463 galaxySED/Burst.50E09.02Z.spec.gz 0.567668319 -0.00274533196 -0.0119206831 0.0424999148 0 0 sersic2d 0.191045119 0.186344383 8427.47647 4 CCM 0.0410986647 3.65929992 CCM 0.0348629307 3.1
[cori12] tail -2 gal_cat_1418971.txt
object 22211487851 0.210310216 0.0859759536 26.539544162524827 galaxySED/Exp.80E09.02Z.spec.gz 0.944681644 -0.00799777173 0.00228374032 0.046026919 0 0 sersic2d 0.154901279 0.0999293893 5414.86936 1 CCM 0.0122921916 1.83792412 CCM 0.0900171813 3.1
object 22211491947 0.148901242 0.142394226 25.396168301060726 galaxySED/Exp.62E09.1Z.spec.gz 0.94481349 0.0108208656 0.00303361891 0.0596093684 0 0 sersic2d 0.0536121071 0.0266171839 7070.28953 1 CCM 0.962943863 2.59028655 CCM 0.0975285515 3.1
[cori12] tail -2 gal_cat_230.txt
object 22211487851 54.5144452 -27.6595809 26.539544162524827 galaxySED/Exp.80E09.02Z.spec.gz 0.944681644 -0.00799777173 0.00228374032 0.046026919 0 0 sersic2d 0.154901279 0.0999293893 5414.86936 1 CCM 0.0122921916 1.83792412 CCM 0.033931612 3.1
object 22211491947 54.431379 -27.6203499 25.396168301060726 galaxySED/Exp.62E09.1Z.spec.gz 0.94481349 0.0108208656 0.00303361891 0.0596093684 0 0 sersic2d 0.0536121071 0.0266171839 7070.28953 1 CCM 0.962943863 2.59028655 CCM 0.0331067277 3.1
[cori12]
```
So this seems to work fine.  There is one oddity:  If I set `db.field_ra = 0` and `db.field_dec =0`, no galaxies are returned.   If not for that issue, I would say that `DESCQAObject_protoDC2` and subclasses could just replace the existing `DESCQAObject` hierarchy.
Any thoughts on why that particular edge case fails?

**Comment by danielsf** [comment]
`lsst.sims.utils.rotationMatrixFromVectors` returns a 3x3 matrix of `NaN`s if you ask it to rotate a vector into itself.  That should obviously be fixed on the LSST side.  I will add a quick fix here that, if you set the field to RA=0, Dec=0, it will not do a rotation

**Comment by jchiang87** [comment]
Thanks, Scott, that fix works fine.  In order to define the sky rotation uniquely for every point in the protoDC2 field, we should also provide a third angle, in addition to the RA, Dec of the new protoDC2 center.  This will allow us to set the orientation of the translated field and would just be a rotation about the new protoDC2 center.  It looks like we would just generate a second rotation matrix using the same axis-angle formulae and left-multiply the current `._field_rot_matrix` by that second matrix.  Is that the best way to do this?

**Comment by danielsf** [comment]
That is how I would do it (I think).

What should the API look like?  Should we be setting the RA, Dec of a reference object in the protoDC2 catalog, or specifying an angle eastward of north to rotate the field by, or something else I'm not thinking of?

**Comment by jchiang87** [comment]
Thinking about this some more, I think we need to worry about the impact of the sky rotation on the WL shears.  Since the WL shears are defined via PAs wrt Celestial north, I think we should define an orientation angle psi such that if psi=0, any two points that lie on a great circle passing through NCP in the original protoDC2 field also lie on a great circle passing through NCP in the new protoDC2 position.  That psi would imply a rotation angle phi (a function of the RA, Dec of the new protoDC2 center) wrt north that we would need to rotate the new field to get that orientation.  As a practical matter for Run1.1, I think we would want to keep psi=0 so that the orientations of WL shears wrt any intrinsic alignments of galaxies are preserved. (There may not be any IAs in protoDC2, but we should be careful about this for the future.)  For non-zero psi, we'd also need to rotate the WL PAs.  I'm not sure we want to try to implement that for Run1.1.

**Comment by danielsf** [comment]
How true do we need this to be?  If you imagine taking a grid of points defined at the equator (which protoDC2 is) and translating it up to the North Celestial Pole, it should not be possible to guarantee that all points related by dRA==0, dDec!=0 still have that relationship in the new location.  The degree to which the relationship breaks down will depend on the size of the catalog (protoDC2 is 5 degrees by 5 degrees) and how far north/south we are translating to get to the actual DC2 field.

What is the declination of the actual DC2 field we are simulating?

**Comment by jchiang87** [comment]
Yes, I worried about that too.   The translated region will contain the Twinkles field, which is centered at RA=54.36, Dec=-27.75.

**Comment by danielsf** [comment]
Okay.  I will try to come up with a solution that minimizes the distortion for a set of test points at `RA=0`, `Dec=np.arange(-2.5, 2.5, 0.1)` in the original protoDC2 field

**Comment by danielsf** [comment]
I think this will work

**Comment by jchiang87** [comment]
Thanks, Scott!  I re-ran the instance catalog generation script for visits 1418971 (near the center of the un-translated protoDC2 field) and for visit 203 (one of the Twinkles visits) and set the target locations to be the nominal pointing of each visit.  Then I ran imsim on the resulting catalogs, having applied `grep -v point` so that only galaxies would be simulated.  Here is the result:
galaxies_1418971_vs_203
On the left is 1418971 and on the right 203.  To my eye, they look like rotated versions of each other, i.e., the galaxy axis orientations wrt their relative positions is preserved.  We'd need to analyze the images in detail to get a quantitative assessment, but I think this definitely passes visual inspection.

**Review by jchiang87 — APPROVED** [review]
Looks good to me.  I think this is ready to merge.  Thanks, Scott.

**Comment by danielsf** [comment]
I don't see the big green "Merge" button in my browser.  I think you will have to merge it, @jchiang87

**Comment by jchiang87** [comment]
@danielsf I obtained admin privileges for this repo and enabled write access for the Computing Infrastructure and Pipelines teams in LSSTDESC, so you should now have write access to this repo.

**Pull request merged**
