### PR TITLE
Assign agn params

### PR DESCRIPTION
**Pull request by danielsf**

### CODE REVIEW

**Comment by danielsf** [comment]
@jbkalmbach

**Comment by danielsf** [comment]
@jbkalmbach 

I think this should fix it.  There have been some API changes.  `workspace/agn_params/test_agn_compound.py` is a version of your test script designed to work with my fixes (and access a db of AGN parameters in my NERSC scratchspace).

Once again, our reliance on parameter-passing-through-class-definition has proven a barrier.  The right way to do construct a `CompoundDESCQAObject` now is to write a class that inherits from `GalaxyCompounDESCQAObject`.  In the class definition, set `agn_params_db` equal to the path to your parameter db and `agn_objid` to the `objid` assigned to your AGN catalog class.

This might be a little clunky for general purposes, but I think we are coding towards *our* purposes at the moment.

Let me know if you have any other troubles.

**Comment by jbkalmbach** [comment]
Ok, this is working for me now. I'm good to merge and I can start testing my twinkles DC2 branch.

**Review by jbkalmbach — APPROVED** [review]

**Comment by danielsf** [comment]
(can't wait to see what rebasing this against EiffL's "galaxy knots" PR looks like...)

**Comment by danielsf** [comment]
As expected, the rebase was fun.  I am going to close this PR and open a new one against the rebased branch.

**Pull request closed without merging**
