### PR TITLE
Fixed CCM string to 'none' by changing default columns. Tested on cori.

### LINKED ISSUE #35: Fix instance catalog output with SN
@jchiang87 reported two problems with SN instance catalogs:
- [x] Has two 'CCM' string in each instance catalog record even though no internal extinction is provided.  This needs to change to either replacing the first 'CCM' to  'none' or provide internal extinction values. 
- [ ] A empty file output of `None` is created by the `generateInstanceCatalogs.py` related to sprinkler outputs. (This is a fix that needs to be done on catsim SIMS-2594)

### PR DESCRIPTION
**Pull request by rbiswas4**
and found test scripts to work:
	modified:   CatalogClasses.py

The output is now of the form:
```
object 32011307 53.3526927 -28.2014438 29.4820118
Dynamic/specFileSN_31261_59844.2240_r.dat 0.965175454 0 0 0 0 0 point
none CCM 0.0280743331 3.1
```

Fixes #35

### CODE REVIEW

**Review by jchiang87 — APPROVED** [review]
looks good.

**Comment by jchiang87** [comment]
I'll go ahead and merge this at 3pm PDT today, unless I hear otherwise.

**Comment by danielsf** [comment]
Should we actually remove `InternalRv` and `InternalAv` from `DC2PhosimCatalogSN.default_columns`?  I am worrying about a scenario in which `internalRv`  and `internalAv` accidentally get added to `column_outputs` for `DC2PhosimCatalogSN` (possibly through some misguided class inheritance).  In that case, the internal dust model will be `None`, but there will be numerical values for `internalRv` and `internalAv`, which I can't imagine PhoSim will handle well.  If we remove `internalRv` and `internalAv` from `default_columns`, the catalog generation code will complain if we ever ask it to output `internalRv` or `internalAv`.

**Comment by rbiswas4** [comment]
@danielsf  I should state that I intend to add  SN values`internalAV` and `internalRv` to the next set of runs.

**Comment by danielsf** [comment]
OK

**Pull request merged**
